apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-api-dev
  namespace: default
  labels:
    app: elastic-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-api-dev
  template:
    metadata:
      labels:
        app: elastic-api-dev
    spec:
      containers:
        - name: elastic-api-dev
          image: acrziwo.azurecr.io/elastic-api
          imagePullPolicy: Always
          ports:
            - containerPort: 443

---
apiVersion: v2
kind: Service
metadata:
  name:  elastic-api-dev
  namespace: default
  labels:
    app: elastic-api-dev
spec:
  type: ClusterIP
  selector:
    app: elastic-api-dev
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-elastic
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: reporting-flow-ae.ziwo.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: elastic-api-dev
                port:
                  number: 443
  tls:
    - hosts:
        - reporting-flow-ae.ziwo.io
      secretName: elastic-ziwo-certificate   